# IF PRODUCTION AND DEVELOPMENT BOTH ARE SAME PUT INTO THIS FILE 
version: "3"
services: 
    node-app:
        build: 
            context: .
            args: 
                NODE_ENV: development
        ports: 
            - "3000:3000"
        environment:
            - PORT=3000
