# https://docs.docker.com/compose/compose-file/compose-versioning/

version: "3"
services: 
    node-app:
        build: .
        ports: 
            - "3000:4000"
        volumes: 
            - ./:/app
            - /app/node_modules
        # environment: 
        #     - PORT=3000
        env_file: 
            - ./.env
        